<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TraitementAgent', 'doctrine');

/**
 * BaseTraitementAgent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_traitement_agent
 * @property string $commentaire_agent
 * @property integer $id_qualif_agent
 * @property integer $id_question
 * @property integer $id_agent
 * @property QualificationAgent $QualificationAgent
 * @property Question $Question
 * @property Utilisateur $Utilisateur
 * 
 * @method integer            getIdTraitementAgent()   Returns the current record's "id_traitement_agent" value
 * @method string             getCommentaireAgent()    Returns the current record's "commentaire_agent" value
 * @method integer            getIdQualifAgent()       Returns the current record's "id_qualif_agent" value
 * @method integer            getIdQuestion()          Returns the current record's "id_question" value
 * @method integer            getIdAgent()             Returns the current record's "id_agent" value
 * @method QualificationAgent getQualificationAgent()  Returns the current record's "QualificationAgent" value
 * @method Question           getQuestion()            Returns the current record's "Question" value
 * @method Utilisateur        getUtilisateur()         Returns the current record's "Utilisateur" value
 * @method TraitementAgent    setIdTraitementAgent()   Sets the current record's "id_traitement_agent" value
 * @method TraitementAgent    setCommentaireAgent()    Sets the current record's "commentaire_agent" value
 * @method TraitementAgent    setIdQualifAgent()       Sets the current record's "id_qualif_agent" value
 * @method TraitementAgent    setIdQuestion()          Sets the current record's "id_question" value
 * @method TraitementAgent    setIdAgent()             Sets the current record's "id_agent" value
 * @method TraitementAgent    setQualificationAgent()  Sets the current record's "QualificationAgent" value
 * @method TraitementAgent    setQuestion()            Sets the current record's "Question" value
 * @method TraitementAgent    setUtilisateur()         Sets the current record's "Utilisateur" value
 * 
 * @package    juriste
 * @subpackage model
 * @author     Nacef LABIDI <nacef.labidi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTraitementAgent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('traitement_agent');
        $this->hasColumn('id_traitement_agent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('commentaire_agent', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('id_qualif_agent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_question', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_agent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QualificationAgent', array(
             'local' => 'id_qualif_agent',
             'foreign' => 'id_qualif_agent'));

        $this->hasOne('Question', array(
             'local' => 'id_question',
             'foreign' => 'id_question'));

        $this->hasOne('Utilisateur', array(
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'date_creation',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'name' => 'date_modification',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             ));
        $this->actAs($timestampable0);
    }
}