<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rdv', 'doctrine');

/**
 * BaseRdv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_rdv
 * @property timestamp $date_debut_rdv
 * @property timestamp $date_fin_rdv
 * @property integer $id_avocat
 * @property integer $id_vente
 * @property string $commentaire_avocat
 * @property Utilisateur $Utilisateur
 * @property Vente $Vente
 * 
 * @method integer     getIdRdv()              Returns the current record's "id_rdv" value
 * @method timestamp   getDateDebutRdv()       Returns the current record's "date_debut_rdv" value
 * @method timestamp   getDateFinRdv()         Returns the current record's "date_fin_rdv" value
 * @method integer     getIdAvocat()           Returns the current record's "id_avocat" value
 * @method integer     getIdVente()            Returns the current record's "id_vente" value
 * @method string      getCommentaireAvocat()  Returns the current record's "commentaire_avocat" value
 * @method Utilisateur getUtilisateur()        Returns the current record's "Utilisateur" value
 * @method Vente       getVente()              Returns the current record's "Vente" value
 * @method Rdv         setIdRdv()              Sets the current record's "id_rdv" value
 * @method Rdv         setDateDebutRdv()       Sets the current record's "date_debut_rdv" value
 * @method Rdv         setDateFinRdv()         Sets the current record's "date_fin_rdv" value
 * @method Rdv         setIdAvocat()           Sets the current record's "id_avocat" value
 * @method Rdv         setIdVente()            Sets the current record's "id_vente" value
 * @method Rdv         setCommentaireAvocat()  Sets the current record's "commentaire_avocat" value
 * @method Rdv         setUtilisateur()        Sets the current record's "Utilisateur" value
 * @method Rdv         setVente()              Sets the current record's "Vente" value
 * 
 * @package    juriste
 * @subpackage model
 * @author     Nacef LABIDI <nacef.labidi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRdv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rdv');
        $this->hasColumn('id_rdv', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date_debut_rdv', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_fin_rdv', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_avocat', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_vente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('commentaire_avocat', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'id_avocat',
             'foreign' => 'id_utilisateur'));

        $this->hasOne('Vente', array(
             'local' => 'id_vente',
             'foreign' => 'id_vente'));
    }
}