<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dispatch', 'doctrine');

/**
 * BaseDispatch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_dispatch
 * @property integer $questions
 * @property integer $id_agent
 * @property Utilisateur $Utilisateur
 * 
 * @method integer     getIdDispatch()  Returns the current record's "id_dispatch" value
 * @method integer     getQuestions()   Returns the current record's "questions" value
 * @method integer     getIdAgent()     Returns the current record's "id_agent" value
 * @method Utilisateur getUtilisateur() Returns the current record's "Utilisateur" value
 * @method Dispatch    setIdDispatch()  Sets the current record's "id_dispatch" value
 * @method Dispatch    setQuestions()   Sets the current record's "questions" value
 * @method Dispatch    setIdAgent()     Sets the current record's "id_agent" value
 * @method Dispatch    setUtilisateur() Sets the current record's "Utilisateur" value
 * 
 * @package    juriste
 * @subpackage model
 * @author     Nacef LABIDI <nacef.labidi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDispatch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dispatch');
        $this->hasColumn('id_dispatch', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('questions', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_agent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur'));
    }
}