<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QualificationAgent', 'doctrine');

/**
 * BaseQualificationAgent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_qualif_agent
 * @property string $texte_qualification
 * @property Doctrine_Collection $TraitementAgent
 * 
 * @method integer             getIdQualifAgent()       Returns the current record's "id_qualif_agent" value
 * @method string              getTexteQualification()  Returns the current record's "texte_qualification" value
 * @method Doctrine_Collection getTraitementAgent()     Returns the current record's "TraitementAgent" collection
 * @method QualificationAgent  setIdQualifAgent()       Sets the current record's "id_qualif_agent" value
 * @method QualificationAgent  setTexteQualification()  Sets the current record's "texte_qualification" value
 * @method QualificationAgent  setTraitementAgent()     Sets the current record's "TraitementAgent" collection
 * 
 * @package    juriste
 * @subpackage model
 * @author     Nacef LABIDI <nacef.labidi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQualificationAgent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qualification_agent');
        $this->hasColumn('id_qualif_agent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('texte_qualification', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TraitementAgent', array(
             'local' => 'id_qualif_agent',
             'foreign' => 'id_qualif_agent'));
    }
}