<?php

/**
 * RappelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RappelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RappelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rappel');
    }
}