<?php

/**
 * RdvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RdvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RdvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rdv');
    }
}