<?php

/**
 * TraitementAgentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TraitementAgentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TraitementAgentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TraitementAgent');
    }
}