<?php

/**
 * TraitementAvocatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TraitementAvocatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TraitementAvocatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TraitementAvocat');
    }
}