<?php

/**
 * UtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utilisateur');
    }
}