<?php

/**
 * VenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vente');
    }
}