<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('rdv', 'rdv_id_avocat_utilisateur_id_utilisateur', array(
             'name' => 'rdv_id_avocat_utilisateur_id_utilisateur',
             'local' => 'id_avocat',
             'foreign' => 'id_utilisateur',
             'foreignTable' => 'utilisateur',
             ));
        $this->createForeignKey('rdv', 'rdv_id_vente_vente_id_vente', array(
             'name' => 'rdv_id_vente_vente_id_vente',
             'local' => 'id_vente',
             'foreign' => 'id_vente',
             'foreignTable' => 'vente',
             ));
        $this->createForeignKey('traitement_agent', 'tiqi', array(
             'name' => 'tiqi',
             'local' => 'id_qualif_agent',
             'foreign' => 'id_qualif_agent',
             'foreignTable' => 'qualification_agent',
             ));
        $this->createForeignKey('traitement_agent', 'traitement_agent_id_question_question_id_question', array(
             'name' => 'traitement_agent_id_question_question_id_question',
             'local' => 'id_question',
             'foreign' => 'id_question',
             'foreignTable' => 'question',
             ));
        $this->createForeignKey('traitement_agent', 'traitement_agent_id_agent_utilisateur_id_utilisateur', array(
             'name' => 'traitement_agent_id_agent_utilisateur_id_utilisateur',
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur',
             'foreignTable' => 'utilisateur',
             ));
        $this->createForeignKey('vente', 'vente_id_question_question_id_question', array(
             'name' => 'vente_id_question_question_id_question',
             'local' => 'id_question',
             'foreign' => 'id_question',
             'foreignTable' => 'question',
             ));
        $this->createForeignKey('vente', 'vente_id_agent_utilisateur_id_utilisateur', array(
             'name' => 'vente_id_agent_utilisateur_id_utilisateur',
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur',
             'foreignTable' => 'utilisateur',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('rdv', 'rdv_id_avocat_utilisateur_id_utilisateur');
        $this->dropForeignKey('rdv', 'rdv_id_vente_vente_id_vente');
        $this->dropForeignKey('traitement_agent', 'tiqi');
        $this->dropForeignKey('traitement_agent', 'traitement_agent_id_question_question_id_question');
        $this->dropForeignKey('traitement_agent', 'traitement_agent_id_agent_utilisateur_id_utilisateur');
        $this->dropForeignKey('vente', 'vente_id_question_question_id_question');
        $this->dropForeignKey('vente', 'vente_id_agent_utilisateur_id_utilisateur');
    }
}