<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dispatch', 'dispatch_id_agent_utilisateur_id_utilisateur', array(
             'name' => 'dispatch_id_agent_utilisateur_id_utilisateur',
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur',
             'foreignTable' => 'utilisateur',
             ));
        $this->addIndex('dispatch', 'dispatch_id_agent', array(
             'fields' => 
             array(
              0 => 'id_agent',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dispatch', 'dispatch_id_agent_utilisateur_id_utilisateur');
        $this->removeIndex('dispatch', 'dispatch_id_agent', array(
             'fields' => 
             array(
              0 => 'id_agent',
             ),
             ));
    }
}