<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addqualificationagent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('qualification_agent', array(
             'id_qualif_agent' => 
             array(
              'type' => 'integer',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'texte_qualification' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => 45,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id_qualif_agent',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('qualification_agent');
    }
}