<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('question', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('question', 'date_question', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('question', 'updated_at');
    }
}