<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('rappel', 'rappel_id_question_question_id_question', array(
             'name' => 'rappel_id_question_question_id_question',
             'local' => 'id_question',
             'foreign' => 'id_question',
             'foreignTable' => 'question',
             ));
        $this->createForeignKey('rappel', 'rappel_id_agent_utilisateur_id_utilisateur', array(
             'name' => 'rappel_id_agent_utilisateur_id_utilisateur',
             'local' => 'id_agent',
             'foreign' => 'id_utilisateur',
             'foreignTable' => 'utilisateur',
             ));
        $this->addIndex('rappel', 'rappel_id_question', array(
             'fields' => 
             array(
              0 => 'id_question',
             ),
             ));
        $this->addIndex('rappel', 'rappel_id_agent', array(
             'fields' => 
             array(
              0 => 'id_agent',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('rappel', 'rappel_id_question_question_id_question');
        $this->dropForeignKey('rappel', 'rappel_id_agent_utilisateur_id_utilisateur');
        $this->removeIndex('rappel', 'rappel_id_question', array(
             'fields' => 
             array(
              0 => 'id_question',
             ),
             ));
        $this->removeIndex('rappel', 'rappel_id_agent', array(
             'fields' => 
             array(
              0 => 'id_agent',
             ),
             ));
    }
}