<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('traitement_avocat', 'tiqi_1', array(
             'name' => 'tiqi_1',
             'local' => 'id_qualif_agent',
             'foreign' => 'id_qualif_agent',
             'foreignTable' => 'qualification_agent',
             ));
        $this->createForeignKey('traitement_avocat', 'traitement_avocat_id_question_question_id_question', array(
             'name' => 'traitement_avocat_id_question_question_id_question',
             'local' => 'id_question',
             'foreign' => 'id_question',
             'foreignTable' => 'question',
             ));
        $this->addIndex('traitement_avocat', 'traitement_avocat_id_qualif_agent', array(
             'fields' => 
             array(
              0 => 'id_qualif_agent',
             ),
             ));
        $this->addIndex('traitement_avocat', 'traitement_avocat_id_question', array(
             'fields' => 
             array(
              0 => 'id_question',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('traitement_avocat', 'tiqi_1');
        $this->dropForeignKey('traitement_avocat', 'traitement_avocat_id_question_question_id_question');
        $this->removeIndex('traitement_avocat', 'traitement_avocat_id_qualif_agent', array(
             'fields' => 
             array(
              0 => 'id_qualif_agent',
             ),
             ));
        $this->removeIndex('traitement_avocat', 'traitement_avocat_id_question', array(
             'fields' => 
             array(
              0 => 'id_question',
             ),
             ));
    }
}