<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('vente', 'montant', 'double', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('vente', 'numero_cc', 'string', '16', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             'creditcard' => '1',
             ));
        $this->changeColumn('vente', 'cvv2', 'string', '3', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('vente', 'nom', 'string', '45', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
        $this->changeColumn('vente', 'prenom', 'string', '45', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             ));
    }

    public function down()
    {

    }
}