<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('rappel', 'cloture', 'boolean', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('rappel', 'cloture');
    }
}