<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('traitement_agent', 'priorite', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '1',
             'autoincrement' => '',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('traitement_agent', 'priorite');
    }
}